# Generated by Django 2.2.5 on 2019-11-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_type_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tacgia',
            field=models.CharField(default='', max_length=200, verbose_name='tacgia'),
        ),
        migrations.AddField(
            model_name='product',
            name='xuatban',
            field=models.CharField(default='', max_length=200, verbose_name='xuatban'),
        ),
    ]
