# Generated by Django 2.2.5 on 2019-11-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20191110_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.FileField(default='', upload_to='uploadsfile/%Y/%m/%d/'),
        ),
    ]
